openapi: 3.1.0
info:
  title: Backend Toko API
  version: 0.2.0
paths:
  /api/v1/auth/register:
    post:
      summary: Register
  /api/v1/auth/login:
    post:
      summary: Login
  /api/v1/auth/refresh:
    post:
      summary: Refresh access token via cookie
  /api/v1/auth/logout:
    post:
      summary: Logout and revoke refresh session
  /api/v1/auth/me:
    get:
      summary: Me
  /api/v1/auth/password/forgot:
    post:
      summary: Send password reset email
  /api/v1/auth/password/reset:
    post:
      summary: Reset password with token
  /api/v1/users/me/addresses:
    get:
      summary: List addresses
    post:
      summary: Create address
  /api/v1/users/me/addresses/{addressID}:
    patch:
      summary: Update address
    delete:
      summary: Delete address
components: {}
