apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-toko-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-toko-api
  template:
    metadata:
      labels:
        app: backend-toko-api
    spec:
      containers:
        - name: api
          image: ghcr.io/org/backend-toko:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: backend-toko-secrets
            - configMapRef:
                name: backend-toko-config
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
            periodSeconds: 10
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "512Mi"
