-- Rollback for the full catalog seed.
-- Generated by scripts/seed/gen_seed_sql.py.
--
-- Only rows this migration seeded are removed. Categories and brands are kept
-- when other products (or the 000007 seed) still reference them, since dropping
-- them would either fail or silently null out unrelated products.

BEGIN;

DELETE FROM products WHERE slug IN ('macbook-pro-14-m3', 'iphone-15-pro', 'samsung-galaxy-s24-ultra', 'sony-wh-1000xm5', 'dell-xps-13-plus', 'canon-eos-r5', 'sony-playstation-5-slim', 'xiaomi-redmi-note-13-pro', 'samsung-smart-tv-55-crystal-uhd', 'apple-ipad-air-11-m2', 'philips-air-fryer-xl', 'nike-air-force-1-low', 'adidas-ultraboost-light', 'uniqlo-airism-cotton-tshirt', 'uniqlo-selvedge-slim-jeans', 'nike-dri-fit-training-shorts', 'adidas-originals-trefoil-hoodie', 'leather-minimalist-wallet', 'classic-analog-watch-steel', 'ikea-landskrona-3-seat-sofa', 'dyson-v15-detect-absolute', 'ikea-markus-office-chair', 'philips-hue-starter-kit', 'bosch-series-4-washing-machine', 'ceramic-dinnerware-set-16', 'memory-foam-mattress-queen', 'the-body-shop-tea-tree-oil', 'wardah-lightening-day-cream', 'niacinamide-serum-10', 'matte-liquid-lipstick-set', 'shimano-road-bike-105', 'adidas-yoga-mat-pro', 'adjustable-dumbbell-set-24kg', 'nike-mercurial-football-boots', 'lego-star-wars-millennium-falcon', 'lego-city-police-station', 'wooden-montessori-puzzle-set', 'rc-drift-car-4wd', 'atomic-habits-indonesia', 'clean-code-robert-martin', 'laut-bercerita-leila-chudori', 'dot-grid-notebook-a5', 'bosch-car-battery-din55', 'dashcam-4k-dual-lens', 'car-vacuum-cordless-mini', 'microfiber-car-care-kit', 'omron-blood-pressure-monitor', 'whey-protein-isolate-2lb', 'vitamin-d3-1000iu-90', 'digital-body-fat-scale', 'bosch-cordless-grass-trimmer', 'terracotta-planter-set-3', 'garden-hose-reel-20m', 'hand-garden-tool-set-5');

DELETE FROM categories c WHERE c.slug IN ('electronics', 'fashion', 'home-living', 'beauty', 'sports', 'toys', 'books', 'automotive', 'health', 'garden')
  AND NOT EXISTS (SELECT 1 FROM products p WHERE p.category_id = c.id)
  AND NOT EXISTS (SELECT 1 FROM categories child WHERE child.parent_id = c.id);

DELETE FROM brands b WHERE b.slug IN ('apple', 'samsung', 'sony', 'dell', 'canon', 'nike', 'adidas', 'uniqlo', 'ikea', 'dyson', 'philips', 'lego', 'the-body-shop', 'wardah', 'gramedia', 'shimano', 'bosch', 'xiaomi', 'acme')
  AND NOT EXISTS (SELECT 1 FROM products p WHERE p.brand_id = b.id);

COMMIT;
