-- Add a human-readable, per-day sequence order number to match the API contract
-- (e.g. ORD-20260724-001). Generated by the checkout service at insert time.
ALTER TABLE orders ADD COLUMN IF NOT EXISTS order_number TEXT;

-- Uniqueness guarantee so concurrent same-day allocations collide loudly instead
-- of silently duplicating. Partial index keeps NULLs (pre-existing rows) out of the
-- way.
CREATE UNIQUE INDEX IF NOT EXISTS idx_orders_order_number_unique
    ON orders (order_number)
    WHERE order_number IS NOT NULL;
